#!/bin/sh
set -e

export PRTE_MCA_rmaps_default_mapping_policy=:oversubscribe

for py in $(py3versions -s 2>/dev/null);
do
    cd "$AUTOPKGTEST_TMP"

    echo "\n=== Testing network support in mpi build with $py ==="
    mpirun -n 4 $py -mpytest -o cache_dir=$AUTOPKGTEST_TMP -v --with-mpi -p no:xvfb -k ros3 /usr/lib/python3/dist-packages/h5py/_debian_h5py_mpi/tests
done
