#!/bin/sh
set -e

for py in $(py3versions -s 2>/dev/null);
do
    cd "$AUTOPKGTEST_TMP"

    echo "\n=== Testing serial build with $py ==="
    $py -c "from sys import exit; import h5py; exit(h5py.run_tests('-v -k \"not ros3\"'))"
done
